KGflex/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name='KGflex'
urlpatterns = [
    path('anime-details', views.KGflexList.as_view(), name='anime-details'),
    path('index', views.KGflex_list, name='list'),
    path('free/<int:pk>/', views.KGflexDetail.as_view(), name='detail'),
    path('create_KGflex/', views.KGflexCreate.as_view(),name='KGflex_create'),
    path('delete_KGflex/<int:pk>/', views.KGflexDelete,name='KGflex_delete'),
    path('update_KGflex/<int:pk>/', views.KGflexUpdate.as_view(),name='KGflex_update'),

    path('notice', views.notice_list.as_view(), name='notice_list'),
    path('notice/<int:pk>/', views.NoticeDetail.as_view(), name='notice_detail'),
    
    
    
    
    
    path('KDrama', views.KDrama_list.as_view(), name='KDrama_list'),
    path('KDrama/<int:pk>/', views.KDramaDetail.as_view(), name='KDrama_detail'),







    path('entertainment', views.entertainment_list.as_view(), name='entertainment_list'),
    path('entertainment/<int:pk>/', views.entertainmentDetail.as_view(), name='entertainment_detail'),





    path('KMovie', views.KMovie_list.as_view(), name='KMovie_list'),
    path('KMovie/<int:pk>/', views.KMovieDetail.as_view(), name='KMovie_detail'),
 



    path('UMovie', views.UMovie_list.as_view(), name='UMovie_list'),
    path('UMovie/<int:pk>/', views.UMovieDetail.as_view(), name='UMovie_detail'),






    path('signup', views.signup , name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='KGflex/login.html'), name='login'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from KGflex import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('KGflex/', include('KGflex.urls')),
    path('', views.KGflex_list, name='KGflex'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KGflex/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from imagekit.models import  ImageSpecField
from imagekit.processors import Thumbnail

# Create your models here.
class KGflex(models.Model):
  title = models.CharField(max_length=30)
  content = models.TextField()
  file_upload = models.FileField(upload_to='KGflex/data/%Y/%m/%d/', blank=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self):
    return f'[PK:{self.pk}]-{self.title} :: {self.author}'

  def get_FileName(self):
    return os.path.basename(self.file_upload.name)

  def get_absolute_url(self):
    return f'/KGflex/free/{self.pk}/'


class Notice(models.Model):
  title = models.CharField(max_length=30)
  content = models.TextField()
  file_upload = models.FileField(upload_to='KGflex/data/%Y/%m/%d/', blank=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self):
    return f'[PK:{self.pk}]-{self.title} :: {self.author}'

  def get_FileName(self):
        return os.path.basename(self.file_upload.name)

  def get_absolute_url(self):
    return f'/KGflex/notice/{self.pk}/'    


class KDrama(models.Model):
  title = models.CharField(max_length=30)
  name = models.CharField(max_length=30, null=True, blank=True)
  content = models.TextField()
  file_upload = models.FileField(upload_to='KGflex/KDrama/')
  photo = models.ImageField(upload_to = 'blog/KDrama')
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self):
    return f'[PK:{self.pk}]-{self.title} :: {self.author}'

  def get_FileName(self):
        return os.path.basename(self.file_upload.name)

  def get_absolute_url(self):
    return f'/KGflex/KDrama/{self.pk}/'    







class entertainment(models.Model):
  title = models.CharField(max_length=30)
  name = models.CharField(max_length=30, null=True, blank=True)
  content = models.TextField()
  file_upload = models.FileField(upload_to='KGflex/entertainment/')
  photo = models.ImageField(upload_to = 'blog/entertainment')
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self):
    return f'[PK:{self.pk}]-{self.title} :: {self.author}'

  def get_FileName(self):
        return os.path.basename(self.file_upload.name)

  def get_absolute_url(self):
    return f'/KGflex/entertainment/{self.pk}/'    






class KMovie(models.Model):
  title = models.CharField(max_length=30)
  name = models.CharField(max_length=30, null=True, blank=True)
  content = models.TextField()
  file_upload = models.FileField(upload_to='KGflex/KMovie/')
  photo = models.ImageField(upload_to = 'blog/KMovie')
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self):
    return f'[PK:{self.pk}]-{self.title} :: {self.author}'

  def get_FileName(self):
        return os.path.basename(self.file_upload.name)

  def get_absolute_url(self):
    return f'/KGflex/KMovie/{self.pk}/'    





class UMovie(models.Model):
  title = models.CharField(max_length=30)
  name = models.CharField(max_length=30, null=True, blank=True)
  content = models.TextField()
  file_upload = models.FileField(upload_to='KGflex/UMovie/')
  photo = models.ImageField(upload_to = 'blog/UMovie')
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self):
    return f'[PK:{self.pk}]-{self.title} :: {self.author}'

  def get_FileName(self):
        return os.path.basename(self.file_upload.name)

  def get_absolute_url(self):
    return f'/KGflex/UMovie/{self.pk}/'    







    

  

KGflex/views.py
from django.shortcuts import get_object_or_404, render, redirect
from KGflex.models import KGflex, Notice, KDrama, UMovie, KMovie, entertainment
from django.views.generic import DetailView, ListView, CreateView, UpdateView
from KGflex.forms import UserForm, KGflexCreateForm, KGflexUpdateForm, NoticeCreateForm, NoticeUpdateForm, KDramaCreateForm, KDramaUpdateForm, UMovieCreateForm, UMovieUpdateForm, KMovieCreateForm, KMovieUpdateForm, entertainmentCreateForm, entertainmentUpdateForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from config import settings
import os
from django.core.exceptions import PermissionDenied

# Create your views here.

def KGflex_list(request):
    return render(request, 'KGflex/index.html')

class KGflexDetail(DetailView):
    model = KGflex
    template_name = 'KGflex/KGflex_detail.html'
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
          return super().dispatch(request, *args, **kwargs)
        else:
          raise PermissionDenied

class KGflexList(ListView):
    model = KGflex
    template_name = 'KGflex/anime-details.html'
    ordering = '-pk'
    paginate_by = 10

class KGflexCreate(CreateView):
    model = KGflex
    form_class = KGflexCreateForm
    template_name = 'KGflex/KGflex_form.html'
    
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super().form_valid(form)
        else:
            return redirect('/KGflex')

@login_required(login_url='KGflex:login')
def KGflexDelete(request, pk):
    kgflex = get_object_or_404(KGflex, pk=pk)
    if request.user != kgflex.author:
        return redirect('KGflex:detail', pk=pk)
    if kgflex.file_upload:
        file_upload_path = os.path.join(settings.MEDIA_ROOT, kgflex.file_upload.path)
        if os.path.exists(file_upload_path):
            os.remove(file_upload_path)
    kgflex.delete()
    return redirect('KGflex:anime-details')

class KGflexUpdate(UpdateView):
    model = KGflex
    form_class = KGflexUpdateForm
    template_name = 'KGflex/KGflex_form_update.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
      if self.get_object().file_upload.name != '':
        if self.object.file_upload != self.get_object().file_upload.name:
          file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
          if os.path.exists(file_upload_path):
              os.remove(file_upload_path)
        if 'upload_clear' in self.request.POST:
          file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
          if os.path.exists(file_upload_path):
              os.remove(file_upload_path)
              self.object.file_upload = ''
      return super().form_valid(form)



class NoticeDetail(DetailView):
    model = Notice
    template_name = 'KGflex/notice_detail.html'
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
          return super().dispatch(request, *args, **kwargs)
        else:
          raise PermissionDenied
          
class notice_list(ListView):
    model = Notice
    template_name = 'KGflex/notice.html'
    ordering = '-pk'
    paginate_by = 10

class NoticeCreate(CreateView):
    model = Notice
    form_class = NoticeCreateForm
    template_name = 'KGflex/notice_form.html'
    
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super().form_valid(form)
        else:
            return redirect('/KGflex')

@login_required(login_url='KGflex:login')
def NoticeDelete(request, pk):
    notice = get_object_or_404(Notice, pk=pk)
    if request.user != notice.author:
        return redirect('KGflex:notice_detail', pk=pk)
    if notice.file_upload:
        file_upload_path = os.path.join(settings.MEDIA_ROOT, notice.file_upload.path)
        if os.path.exists(file_upload_path):
            os.remove(file_upload_path)
    notice.delete()
    return redirect('KGflex:notice')

class NoticeUpdate(UpdateView):
    model = Notice
    form_class = NoticeUpdateForm
    template_name = 'KGflex/notice_form_update.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
            

    def form_valid(self, form):
      if self.get_object().file_upload.name != '':
        if self.object.file_upload != self.get_object().file_upload.name:
          file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
          if os.path.exists(file_upload_path):
              os.remove(file_upload_path)
        if 'upload_clear' in self.request.POST:
          file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
          if os.path.exists(file_upload_path):
              os.remove(file_upload_path)
              self.object.file_upload = ''
      return super().form_valid(form)

















class KDramaDetail(DetailView):
    model = KDrama
    template_name = 'KGflex/KDrama_detail.html'
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
          return super().dispatch(request, *args, **kwargs)
        else:
          return redirect('/KGflex/login')
          
class KDrama_list(ListView):
    model = KDrama
    template_name = 'KGflex/KDrama.html'
    ordering = '-pk'
    paginate_by = 6

class KDramaCreate(CreateView):
    model = KDrama
    form_class =KDramaCreateForm
    
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super().form_valid(form)
        else:
            return redirect('/KGflex')

@login_required(login_url='KGflex:login')
def KDramaDelete(request, pk):
    kdrama = get_object_or_404(KDrama, pk=pk)
    if request.user != kdrama.author:
        return redirect('KGflex:KDrama_detail', pk=pk)
    if kdrama.file_upload:
        file_upload_path = os.path.join(settings.MEDIA_ROOT, kdrama.file_upload.path)
        if os.path.exists(file_upload_path):
            os.remove(file_upload_path)
    kdrama.delete()
    return redirect('KGflex:KDrama')





class KDramaUpdate(UpdateView):
    model = KDrama
    form_class = KDramaUpdateForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
      if self.get_object().file_upload.name != '':
        if self.object.file_upload != self.get_object().file_upload.name:
          file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
          if os.path.exists(file_upload_path):
              os.remove(file_upload_path)
        if 'upload_clear' in self.request.POST:
          file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
          if os.path.exists(file_upload_path):
              os.remove(file_upload_path)
              self.object.file_upload = ''
      return super().form_valid(form)
















class UMovieDetail(DetailView):
    model = UMovie
    template_name = 'KGflex/UMovie_detail.html'
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
          return super().dispatch(request, *args, **kwargs)
        else:
          return redirect('/KGflex/login')
          
class UMovie_list(ListView):
    model = UMovie
    template_name = 'KGflex/UMovie.html'
    ordering = '-pk'
    paginate_by = 6

class UMovieCreate(CreateView):
    model = UMovie
    form_class =UMovieCreateForm
    
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super().form_valid(form)
        else:
            return redirect('/KGflex')

@login_required(login_url='KGflex:login')
def UMovieDelete(request, pk):
    umovie = get_object_or_404(UMovie, pk=pk)
    if request.user != umovie.author:
        return redirect('KGflex:UMovie_detail', pk=pk)
    if umovie.file_upload:
        file_upload_path = os.path.join(settings.MEDIA_ROOT, umovie.file_upload.path)
        if os.path.exists(file_upload_path):
            os.remove(file_upload_path)
    umovie.delete()
    return redirect('KGflex:UMovie')





class UMovieUpdate(UpdateView):
    model = UMovie
    form_class = UMovieUpdateForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
      if self.get_object().file_upload.name != '':
        if self.object.file_upload != self.get_object().file_upload.name:
          file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)

templates/KGflex/KDrama.html
{% extends "KGflex_bas.html" %}
{% block content %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="/"><i class="fa fa-home"></i> 홈</a>
                        <a href="#">카테고리</a>
                        <span>국내 드라마</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Product Section Begin -->
    <section class="product-page spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="product__page__content">
                        <div class="product__page__title">
                            <div class="row">
                                <div class="col-lg-8 col-md-8 col-sm-6">
                                    <div class="section-title">
                                        <h4>국내 드라마  </h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                {% include "KGflex_cecece.html" %}
                {% include "KGflex_Week.html" %}
</div>
</div>
</div>
</div>
</section>


{% endblock %}

templates/KGflex/KGflex_detail.html
{% extends "KGflex_bas.html" %}
{% block content %}
<!-- Breadcrumb Begin -->
<div class="breadcrumb-option">
   <div class="container">
       <div class="row">
           <div class="col-lg-12">
               <div class="breadcrumb__links">
                   <a href="/KGflex/index"><i class="fa fa-home"></i> 홈</a>
                   <span>자유 게시판</span>
               </div>
           </div>
       </div>
   </div>
</div>
    <!-- Breadcrumb End -->
    <section class="board_detail-block">
      <div class="container mt-3">
      <div class="card border-dark mb-3">
    
        <div class="card-header">
          <h4 class="pt-1">{{ object.title }}</h4>
          {% if object.modify_date %}
            <p class="pt-1">Created by {{ object.author }} on {{ object.modify_date }}</p>
          {% else %}
            <p class="pt-1">Created by {{ object.author }} on {{ object.create_date }}</p>
          {% endif %}
        </div>
        
        
    
        <div class="card-body text-dark">
          <p class="card-text">{{ object.content | linebreaksbr }}</p>
          <div class="mt-4"></div>
        </div>
        
        <div class="card-footer d-flex justify-content-between">
          <a href="{% url 'KGflex:anime-details' %}" class="btn btn-outline-dark">목록</a>
          {% if user == object.author %}
          <span>
            <a href="{% url 'KGflex:KGflex_update' object.id %}" class="btn btn-outline-dark">수정</a>
            <a href="#" class="delete btn btn-outline-dark" data-uri="{% url 'KGflex:KGflex_delete' object.id %}">삭제</a>
          </span>
          {% else %}
          <span>
            <a href="#" class="user_check btn btn-outline-dark">수정</a>
            <a href="#" class="user_check btn btn-outline-dark">삭제</a>
          </span>
          {% endif %}
        </div>
    
        
      </div>
      </div>
    </section>

  <div class="breadcrumb-option">
      
  </div>
  <div class="breadcrumb-option">
      
  </div>
  <div class="breadcrumb-option">
      
  </div>
  <div class="breadcrumb-option">
      
  </div>

{% endblock %}

{% block script %}

<script type='text/javascript'>
  $(document).ready(function() {
    $(".delete").on('click', function() {
      if(confirm("정말로 삭제하시겠습니까?")) {
        location.href = $(this).data('uri');
      }
    });
  });
  $(document).ready(function() {
    $(".user_check").on('click', function() {
      alert("자신의 게시글만 수정 및 삭제가 가능합니다.")
    });
  });
</script>

{% endblock %}

templates/KGflex/KMovie_detail.html
{% extends "KGflex_bas.html" %}
{% block content %}

{% include "KGflex_dedede.html" %}



{% endblock %}

templates/KGflex/UMovie_detail.html
{% extends "KGflex_bas.html" %}
{% block content %}

{% include "KGflex_dedede.html" %}




{% endblock %}

templates/KGflex/anime-details.html
{% extends "KGflex_bas.html" %}
{% block content %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="/KGflex/index"><i class="fa fa-home"></i> 홈</a>
                        <span>자유 게시판</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->
    <div class="breadcrumb-option">
            
    </div>

    <!-- Anime Section Begin -->
        <section class="anime-details spad">
                    <!-- Board 영역 -->
                    <div class="container">
                        <table class="table table-striped">
                          <!-- Table Head 영역 -->
                            <thead class="thead-dark">
                              <tr class="text-center">
                                <th>번호</th>
                                <th style="width:50%">제목</th>
                                <th>글쓴이</th>
                                <th>작성일</th>
                              </tr>
                            </thead>
                        
                            <!-- Table Body 영역 -->
                            <tbody>
                              {% for board in object_list %}
                              <tr class="text-center">
                                <td>{{ board.id }}</td>
                                {% if user.is_authenticated %}
                                  <td><a class="text-reset text-decoration-none" href="{{ board.get_absolute_url }}">
                                  {{ board.title }}</a></td>
                                {% else %}
                                  <td><a class="login_check text-reset text-decoration-none">
                                  {{ board.title }}</a></td>
                                {% endif %}
                                <td>{{ board.author }}</td>
                                {% if object.modify_date %}
                                <td>{{ board.modify_date }}</td>
                                {% else %}
                                <td>{{ board.create_date }}</td>
                                {% endif %}
                              </tr>
                              {% endfor %}
                            </tbody>
  
                        </table><br>
                      
                        {% if page_obj.paginator.count >= page_obj.paginator.per_page %}
                            <!-- pagination 영역 -->
                            <ul class="pagination justify-content-center">
                                {% if page_obj.has_previous %}
                                <li class="page-item">
                                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
                                </li>
                                {% else %}
                                <li class="page-item disalbed"><a class="page-link" href="#">이전</a></li>
                                {% endif %}
      
                                {% for page_number in page_obj.paginator.page_range %}
                                {% if page_number >= page_obj.number|add:-3 and page_number <= page_obj.number|add:3 %}
                                  {% if page_number == page_obj.number %}
                                    <li class="page-item active">
                                      <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                                    </li>
                                  {% else %}
                                    <li class="page-item">
                                      <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                                    </li>
                                  {% endif %}
                                {% endif %}
                                {% endfor %}
                                
                                {% if page_obj.has_next %}
                                <li class="page-item">
                                  <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
                                </li>
                                {% else %}
                                <li class="page-item disalbed"><a class="page-link" href="#">다음</a></li>
                                {% endif %}
                            </ul>
                        {% endif %}
                        {% if user.is_anonymous %}
                        <div class="blog__details__tags">
                            <a href="/KGflex/login">로그인</a>
                        </div>
                        {% else %}  
                        <div class="blog__details__tags">
                            <a class="nav-link" href="{% url 'KGflex:KGflex_create' %}">글쓰기</a>
                        </div>
                        {% endif %}
                    </div>
        </section>

        <div class="breadcrumb-option">
      
        </div>
        <div class="breadcrumb-option">
            
        </div>
        <div class="breadcrumb-option">
            
        </div>
        <div class="breadcrumb-option">
            
        </div>        
{% endblock %}
{% block script %}
<script type='text/javascript'>
  $(document).ready(function() {
    $(".login_check").on('click', function() {
      alert("로그인 후 이용이 가능합니다.")
    });
  });
</script>
{% endblock %}

templates/KGflex/login.html
{% extends "KGflex_bas.html" %}
{% block content %}
    <!-- Normal Breadcrumb Begin -->
    <section class="normal-breadcrumb set-bg" data-setbg="/static/img/KR-ko-20220815-popsignuptwoweeks-perspective_alpha_website_large.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="normal__breadcrumb__text">
                        <h2>로그인</h2>
                        <p>KGflex에 오신 것을 환영합니다</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Normal Breadcrumb End -->

    <!-- Login Section Begin -->
    <section class="login spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="login__form">
                        <h3>로그인</h3>
                        <form method="post" action="{% url 'KGflex:login' %}">
                          {% csrf_token %}
                          {% include 'form_errors.html' %}  
                            <div class="input__item">
                                <input type="text" class="form-control" name="username" id="username" placeholder="ID"
                                  value="{{ form.username.value | default_if_none:'' }}">
                                <span class="icon_profile"></span>
                            </div>
                            <div class="input__item">
                                <input type="password" class="form-control" name="password" id="password" 
                                  placeholder="Password" value="{{ form.password.value | default_if_none:'' }}">
                                <span class="icon_lock"></span>
                            </div>
                            <button type="submit" class="site-btn">로그인</button>
                        </form>
                        <a href="#" class="forget_pass">비밀번호를 잃어버렸나요?</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="login__register">
                        <h3>혹시 회원이 아니신가요?</h3>
                        <a href="{% url 'KGflex:signup' %}" class="primary-btn">회원가입</a>
                    </div>
                </div>
            </div>
            <div class="login__social">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6">
                        <div class="login__social__links">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Login Section End -->



{% endblock %}

templates/KGflex/notice_detail.html
{% extends "KGflex_bas.html" %}
{% block content %}
<!-- Breadcrumb Begin -->
<div class="breadcrumb-option">
   <div class="container">
       <div class="row">
           <div class="col-lg-12">
               <div class="breadcrumb__links">
                   <a href="/KGflex/index"><i class="fa fa-home"></i> 홈</a>
                   <span>자유 게시판</span>
               </div>
           </div>
       </div>
   </div>
</div>
    <!-- Breadcrumb End -->
    <section class="board_detail-block">
      <div class="container mt-3">
       <div class="card border-dark mb-3">
    
        <div class="card-header">
          <h4 class="pt-1">{{ object.title }}</h4>
          {% if object.modify_date %}
            <p class="pt-1">Created by {{ object.author }} on {{ object.modify_date }}</p>
          {% else %}
            <p class="pt-1">Created by {{ object.author }} on {{ object.create_date }}</p>
          {% endif %}
        </div>
        
        <div class="card-header">
          {% if object.file_upload %}
          <a href="{{ object.file_upload.url }}" class="text-decoration-none text-muted" role="button" download>
            첨부파일 : <i class="fa-solid fa-file-lines me-2"></i>{{object.get_FileName}}
          </a>
          {% else %}
          <a class="text-decoration-none text-muted">첨부파일 : </a>
          {% endif %}
        </div>
    
        <div class="card-body text-dark">
          <p class="card-text">{{ object.content | linebreaksbr }}</p>
          <div class="mt-4"></div>
        </div>
        
        <div class="card-footer d-flex justify-content-between">
          <a href="{% url 'KGflex:notice_list' %}" class="btn btn-outline-dark">목록</a>
          
        </div>
    
        
       </div>
      </div>
    </section>

  <div class="breadcrumb-option">
      
  </div>
  <div class="breadcrumb-option">
      
  </div>
  <div class="breadcrumb-option">
      
  </div>
  <div class="breadcrumb-option">
      
  </div>

{% endblock %}

{% block script %}

<script type='text/javascript'>
  $(document).ready(function() {
    $(".delete").on('click', function() {
      if(confirm("정말로 삭제하시겠습니까?")) {
        location.href = $(this).data('uri');
      }
    });
  });
  $(document).ready(function() {
    $(".user_check").on('click', function() {
      alert("자신의 게시글만 수정 및 삭제가 가능합니다.")
    });
  });
</script>

{% endblock %}