KGflex/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name='KGflex'
urlpatterns = [
    path('anime-details', views.KGflexList.as_view(), name='anime-details'),
    path('index', views.KGflex_list, name='list'),
    path('free/<int:pk>/', views.KGflexDetail.as_view(), name='detail'),
    path('create_KGflex/', views.KGflexCreate.as_view(),name='KGflex_create'),
    path('delete_KGflex/<int:pk>/', views.KGflexDelete,name='KGflex_delete'),
    path('update_KGflex/<int:pk>/', views.KGflexUpdate.as_view(),name='KGflex_update'),

    path('notice', views.notice_list.as_view(), name='notice_list'),
    path('notice/<int:pk>/', views.NoticeDetail.as_view(), name='notice_detail'),
    
    
    
    
    
    path('KDrama', views.KDrama_list.as_view(), name='KDrama_list'),
    path('KDrama/<int:pk>/', views.KDramaDetail.as_view(), name='KDrama_detail'),







    path('entertainment', views.entertainment_list.as_view(), name='entertainment_list'),
    path('entertainment/<int:pk>/', views.entertainmentDetail.as_view(), name='entertainment_detail'),





    path('KMovie', views.KMovie_list.as_view(), name='KMovie_list'),
    path('KMovie/<int:pk>/', views.KMovieDetail.as_view(), name='KMovie_detail'),
 



    path('UMovie', views.UMovie_list.as_view(), name='UMovie_list'),
    path('UMovie/<int:pk>/', views.UMovieDetail.as_view(), name='UMovie_detail'),






    path('signup', views.signup , name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='KGflex/login.html'), name='login'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from KGflex import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('KGflex/', include('KGflex.urls')),
    path('', views.KGflex_list, name='KGflex'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/KGflex_Week.html

<div class="col-lg-4 col-md-6 col-sm-8">
    <div class="product__sidebar">
        <div class="product__sidebar__view">
            <div class="section-title">
                <h5>인기 영상</h5>
            </div>
            <ul class="filter__controls">
                <li class="active" data-filter="*">Day</li>
                <li data-filter=".week">Week</li>
                <li data-filter=".month">Month</li>
                <li data-filter=".years">Years</li>
            </ul>
            <div class="filter__gallery">
                <div class="product__sidebar__view__item set-bg mix week day"
                data-setbg="/static/img/trending/Woo.jpg">
                <h5><a href="/KGflex/KDrama/4/">이상한 변호사 우영우</a></h5>
            </div>
            <div class="product__sidebar__view__item set-bg mix month week years"
            data-setbg="/static/img/live/runningman.jpg">
            <h5><a href="/KGflex/entertainment/6/">런닝맨</a></h5>
        </div>
        <div class="product__sidebar__view__item set-bg mix  month years"
        data-setbg="/static/img/live/MyLittleOldBoy.jpg">
        <h5><a href="/KGflex/entertainment/4/">미운우리새끼</a></h5>
    </div>
    <div class="product__sidebar__view__item set-bg mix week"
    data-setbg="/static/img/trending/TodayWebtoon.jpg">
    <h5><a href="/KGflex/KDrama/3/">오늘의 웹툰</a></h5>
</div>

templates/KGflex_bar.html
{% load static %}
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo  text-center">
                        <a href="/KGflex/index">
                            
                            <h5> KGFLEX </h5>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="/">홈</a></li>
                                <li><a href="#">카테고리 <span class="arrow_carrot-down"></span></a>
                                    <ul class="dropdown">
                                        <li>  <b>추천 메뉴</b> </li>
                                        <li><a href="/KGflex/KDrama">국내 드라마</a></li>
                                        <li><a href="/KGflex/entertainment">예능 프로그램</a></li>
                                        <li><a href="/KGflex/KMovie">국내 영화</a></li>
                                        <li><a href="/KGflex/UMovie">해외 영화</a></li>
                                    </ul>
                                </li>
                                <li><a href="/KGflex/anime-details">자유 게시판</a></li></li>
                                <li><a href="/KGflex/notice">공지사항</a></li></li>
                                <!-- <li><a href="#">Contacts</a></li> -->
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="header__right">
                        {% if user.is_anonymous %}
                            <a class="nav-link" href="{% url 'KGflex:login' %}">
                                <span class="icon_profile"></span>   로그인</a>
                            <a class="nav-link" href="{% url 'KGflex:signup' %}">
                                <span class="icon_profile"></span>   회원가입</a>
                        {% else %}  
                            <a class="nav-link" href="{% url 'KGflex:logout' %}">
                                <i class="fa-solid fa-right-from-bracket me-2"></i>로그아웃 [ {{user.username}} ]</a>
                        {% endif %}
                        <!-- <a href="/KGflex/signup">가입하기</a> -->
                        <!-- <a href="#" class="search-switch"><span class="icon_search"></span></a> -->
                        <!-- <a href="/KGflex/login"><span class="icon_profile"></span></a> -->
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>

templates/KGflex_bas.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>KGflex</title>

    <!-- Bootstrap CDN URL -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"                        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"                              integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  
    <!-- Jquery CDN URL -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" crossorigin="anonymous"></script>

    <!-- Fontawesome URL -->
    <script src="https://kit.fontawesome.com/53e4af2e34.js" crossorigin="anonymous"></script>
  
    
    
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/static/css/plyr.css" type="text/css">
    <link rel="stylesheet" href="/static/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/style1.css" type="text/css">
</head>

<body>
    {% include "KGflex_bar.html" %}
    {% block content %}
    {% endblock %}
    {% block script %}
    {% endblock %}
    {% include "KGflex_foot.html" %}
  </body>
  
  </html>

templates/KGflex_cecece.html
<div class="row">
    <tbody>
        {% for board in object_list %}
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="product__item">
                <div class="product__item__pic set-bg" data-setbg="{{ board.photo.url }}">
                </div>
                <div class="product__item__text">
                    <ul>
                        <li>{{ board.content }}</li>
                    </ul>
                    <h5><a href="{{ board.get_absolute_url }}">{{ board.title }}</a></h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </tbody>
      
</div>
</div>






{% if page_obj.paginator.count >= page_obj.paginator.per_page %}
<!-- pagination 영역 -->
<ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
  </li>
  {% else %}
  <li class="page-item disalbed"><a class="page-link" href="#">이전</a></li>
  {% endif %}
  
  {% for page_number in page_obj.paginator.page_range %}
  {% if page_number >= page_obj.number|add:-3 and page_number <= page_obj.number|add:3 %}
    {% if page_number == page_obj.number %}
      <li class="page-item active">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
      </li>
    {% else %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
      </li>
    {% endif %}
  {% endif %}
  {% endfor %}                    
  {% if page_obj.has_next %}
  <li class="page-item">
    <a class="page-link " href="?page={{ page_obj.next_page_number }}">다음</a>
  </li>
  {% else %}
  <li class="page-item disalbed"><a class="page-link" href="#">다음</a></li>
  {% endif %}
</ul>
{% endif %}                    

</div>

templates/KGflex_dedede.html
<!-- Breadcrumb Begin -->
<div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__links">
                    <a href="/"><i class="fa fa-home"></i> 홈</a>
                    <a href="#">카테고리</a>
                    <a href="/KGflex/KDrama">{{ object.name }}</a>
                    <span>{{ object.title }}</span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<!-- Anime Section Begin -->
<section class="hero spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="anime__video__player">
                    <video id="player" playsinline controls data-poster="{{ object.photo.url }}">
                        <source src="{{object.file_upload.url }}" type="video/mp4" />
                        <!-- Captions are optional -->
                        <track kind="captions" label="English captions" src="#" srclang="en" default />
                    </video>
                </div>
                <div class="anime__details__episodes">
                    <div class="section-title">
                        <h5>{{ object.title }}</h5>

                    </div>
                </div>
            </div>
        </div>
        
    </div>
</section>
<!-- Anime Section End -->

templates/KGflex_foot.html
<!-- Footer Section Begin -->
<footer class="footer">
    <div class="page-up">
        <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="footer__logo">
                    <a href="/KGflex/index"><img src="/static/img/logo1.png" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="footer__nav">
                    <ul>
                        <li class="active"><a href="/KGflex/index">홈</a></li>
                        <li><a href="/KGflex/anime-details">자유 게시판</a></li>
                        <li><a href="/KGflex/notice">공지사항</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3">
                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>

              </div>
          </div>
      </div>
  </footer>
  <!-- Footer Section End -->

  <!-- Search model Begin -->
  <div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch"><i class="icon_close"></i></div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search model end -->

<!-- Js Plugins -->
<script src="/static/js/jquery-3.3.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/player.js"></script>
<script src="/static/js/jquery.nice-select.min.js"></script>
<script src="/static/js/mixitup.min.js"></script>
<script src="/static/js/jquery.slicknav.js"></script>
<script src="/static/js/owl.carousel.min.js"></script>
<script src="/static/js/main.js"></script>

templates/form_errors.html

{% if form.errors %}
  <!-- Field Input Error -->
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{ field.label }} </strong>{{ error }}
      </div>
    {% endfor %}
  {% endfor %}
  
  <!-- Non Field Error -->
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error }}</strong>
    </div>
  {% endfor %} 
{% endif %}

